import Head from 'next/head'
import Image from 'next/image'
import { BsFillMoonStarsFill } from "react-icons/bs"
import { 
  AiFillGithub, 
  AiFillLinkedin, 
  AiFillYoutube 
} from "react-icons/ai"
import profile_pic from '../public/profile_pic.jpeg'
import { useState } from "react"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Zachary Robbins Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-800 dark:text-gray-200">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Zachary Robbins</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className="cursor-pointer text-2xl"/></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">Zachary Robbins</h2>
            <h3 className="text-2xl py-2 md:text-3xl">Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              Pursuing a Bachelor of Science in Software Engineering from Southern New Hampshire University. Interested in web development, data engineering, and computational linguistics.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-200">
            <a href='https://github.com/Xaqiri'><AiFillGithub /></a>
            <a href='https://www.linkedin.com/in/zacharyrobbins-dev/'><AiFillLinkedin /></a>
          </div>
          <div className="relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={profile_pic} layout="fill" objectFit="cover" alt="profile_pic"/>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl pt-1 pb-2">Skills</h3>
            <p className="text-md leading-8 text-gray-800 dark:text-gray-200">
              Web development with React, Python, Django, Java, Spring, Javascript, and Express
            </p>
          </div>
          <div>
            <h3 className="text-3xl pt-2 mb-5 mt-10">Portfolio</h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 text-gray-800 dark:bg-gray-200">
              {/* <Image src={} width={100} height={100}/> */}
              <h3 className="text-lg font-medium pt-8 pb-2"><a className='text-teal-600' href='https://github.com/Xaqiri/PythonFlashcards'>Flashcards</a></h3>
              <p className="py-2">
                Built with Python connected to a cloud-hosted MySQL database
              </p>
            </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10 text-gray-800 dark:bg-gray-200">
                {/* <Image src={} width={100} height={100}/> */}
                <h3 className="text-lg font-medium pt-8 pb-2"><a className='text-teal-600' href='https://topmembersonly.up.railway.app'>Message Board</a></h3>
                <p className="py-2">
                  Simple message board written in Javascript with Node and Express connected to a MongoDB database.
                <p>User authentication with passport.js and password encryption with bcrypt</p>
                </p>
              </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 text-gray-800 dark:bg-gray-200">
              {/* <Image src={} width={100} height={100}/> */}
              <h3 className="text-lg font-medium pt-8 pb-2"><a className='text-teal-600' href='https://github.com/Xaqiri/VampyrManor'>Vampyr Manor</a></h3>
              <p className="py-2">
                Roguelike written in Python + Pygame connected to a Sqlite database
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
            
